version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hotel_postgres
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_password
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: hotel_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - hotel_network

volumes:
  postgres_data:
  qdrant_data:

networks:
  hotel_network:
    driver: bridge 